-- 1 USE PRIMEIRO BD

USE ABD_03361_A_Nilson;

-- 2 CRIAR A TABELA DE CLIENTES_BANCO_ITAU
-- CAMPOS:
-- ID_CLIENTE (INT AUTO_INCREMENT, PRIMARY KEY)
-- NOME_CLIENTE (VARCHAR 100)
-- CPF (VARCHAR 11)
 
 SHOW TABLES;
 
 CREATE TABLE CLIENTES_BANCO_ITAU (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL
);

-- 3 CRIAR A TABELA DE CONTAS
-- CAMPOS:
-- ID_CONTA (INT AUTO_INCREMENT, PRIMARY KEY)
-- ID_CLIENTE (INT, FK)
-- SALDO (DECIMAL 10,2)
-- TIPO_CONTA (VARCHAR 20)

SHOW TABLES;

CREATE TABLE CONTAS (
    ID_CONTA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    SALDO DECIMAL(10,2) DEFAULT 0.00,
    TIPO_CONTA VARCHAR(20) NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES_BANCO_ITAU(ID_CLIENTE)
);

-- 4 POPULAR A TABELA CLIENTES COM 5 CLIENTES SEM DEFINIR AS COLUNAS
 
 INSERT INTO CLIENTES_BANCO_ITAU (NOME_CLIENTE, CPF)
VALUES
('João Silva', '12345678901'),
('Maria Oliveira', '23456789012'),
('Carlos Pereira', '34567890123'),
('Ana Souza', '45678901234'),
('Paulo Santos', '56789012345');

SELECT * FROM CLIENTES_BANCO_ITAU;

-- 5 POPULAR A TABELA CONTAS COM 5 CONTAS

INSERT INTO CONTAS (ID_CLIENTE, SALDO, TIPO_CONTA)
VALUES
(1, 2500.00, 'CORRENTE'),
(2, 1500.50, 'POUPANCA'),
(3, 3200.75, 'SALARIO'),
(4, 800.00, 'CORRENTE'),
(5, 5000.00, 'POUPANCA');

SELECT * FROM CONTAS;

-- 6 EXERCÍCIO DE TRANSAÇÃO COM RELAÇÃO ENTRE CLIENTES E CONTAS
-- SITUAÇÃO: QUEREMOS TRANSFERIR 600 REAIS DE JOÃO SILVA PARA ANA SOUZA
-- PASSO 1: INICIAR A TRANSACAO (BEGIN)
-- PASSO 2: DIMINUIR SALDO DE JOÃO SILVA
-- PASSO 3: AUMENTAR SALDO DE ANA SOUZA

SELECT * FROM CLIENTES_BANCO_ITAU;
SELECT * FROM CONTAS;

START TRANSACTION;
-- DEBITAR 600 REAIS DA CONTA DO JOÃO SILVA
UPDATE CONTAS
SET SALDO = SALDO - 2600
WHERE ID_CLIENTE = 1;
-- CREDITAR 600 REAIS NA CONTA DE ANA SOUZA
UPDATE CONTAS
SET SALDO = SALDO + 2600
WHERE ID_CLIENTE = 4;
-- VERIFICAR O SALDO ATUALIZADO
SELECT * FROM CONTAS;

-- PASSO 4: SE SALDO DE JOÃO FICAR NEGATIVO, FAZER ROLLBACK, SENÃO COMMIT

SELECT * FROM CONTAS;


-- Se SALDO < 0 → ROLLBACK

-- Senão → COMMIT



