USE ABD_03361_A_Nilson;

-- 1 CRIE UMA TABELA CHAMADA COMIDAS_FAVORITAS COM OS CAMPOS: ID, NOME_PESSOA, COMIDA, TIPO, NOTA, CIDADE

CREATE TABLE IF NOT EXISTS COMIDAS_FAVORITAS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PESSOA VARCHAR(100) NOT NULL,
    COMIDA VARCHAR(100) NOT NULL,
    TIPO VARCHAR(50),
    NOTA DECIMAL(3,1) NOT NULL CHECK (NOTA BETWEEN 1 AND 10),
    CIDADE VARCHAR(50)
);

ALTER TABLE COMIDAS_FAVORITAS
CHANGE COLUMN PESSOA NOME_PESSOA VARCHAR(100) NOT NULL;

-- 2 INSIRE 5 REGISTROS NA TABELA COMIDAS_FAVORITAS

INSERT INTO COMIDAS_FAVORITAS (NOME_PESSOA, COMIDA, TIPO, NOTA, CIDADE)
VALUES 
('Nilson Silva', 'Lasanha', 'Massa', 9, 'São Paulo'),
('Laura Almeida', 'Pizza', 'Massa', 10, 'Rio de Janeiro'),
('Carlos Pereira', 'Feijoada', 'Prato Principal', 8, 'Belo Horizonte'),
('Mariana Santos', 'Brigadeiro', 'Doce', 7, 'Curitiba'),
('Vitor Oliveira', 'Churrasco', 'Carne', 10, 'Porto Alegre');

-- 3 SELECIONE TODAS AS COMIDAS COM NOTA MAIOR QUE 8

SELECT *
FROM COMIDAS_FAVORITAS
WHERE NOTA > 8;


-- 4 MOSTRE APENAS O NOME DAS PESSOAS E SUAS COMIDAS FAVORITAS DO TIPO DOCE ORDENADAS PELO NOME

SELECT NOME_PESSOA, COMIDA
FROM COMIDAS_FAVORITAS
WHERE TIPO = 'Doce'
ORDER BY NOME_PESSOA ASC;

-- 5 MOSTRE AS COMIDAS FAVORITAS DE QUEM MORA EM SÃO PAULO OU RIO DE JANEIRO DICA: USE O IN

SELECT NOME_PESSOA, COMIDA
FROM COMIDAS_FAVORITAS
WHERE CIDADE IN ('São Paulo', 'Rio de Janeiro');

-- 6 ATUALIZE A NOTA DE UMA COMIDA ESPECÍFICA PARA 10 DICA: UPDATE NOME_DA_TABELA SET COLUNA = ... WHERE COLUNA = ...

SELECT * FROM COMIDAS_FAVORITAS;

UPDATE COMIDAS_FAVORITAS
SET NOTA = 10
WHERE ID = 4;

SELECT * FROM COMIDAS_FAVORITAS
WHERE COMIDA = 'Brigadeiro';

-- 7 ATUALIZE O TIPO DE TODAS AS COMIDAS QUE CONTENHAM A PALAVRA PIZZA PARA SALGADO DICA: USE LIKE

SET SQL_SAFE_UPDATES = 0;

UPDATE COMIDAS_FAVORITAS
SET TIPO = 'Salgado'
WHERE COMIDA LIKE '%Pizza%';

SET SQL_SAFE_UPDATES = 1; -- opcional, para reativar o modo seguro

SELECT * FROM COMIDAS_FAVORITAS
WHERE COMIDA LIKE '%Pizza%';

-- 8 EXCLUA TODAS AS COMIDAS QUE TENHAM NOTA MENOR QUE 5

SET SQL_SAFE_UPDATES = 0;

DELETE FROM COMIDAS_FAVORITAS
WHERE NOTA < 5;

SET SQL_SAFE_UPDATES = 1; -- reativa o safe mode

-- DESAFIO
-- 9 MOSTRE O NOME DA PESSOA E A COMIDA FAVORITA ONDE O NOME_TENHA MAIS DE 10 CARACTERES
-- E A NOTA ESTEJA ENTRE 7 E 10 DICA: USE LENGTH() E BETWEEN

SELECT NOME_PESSOA, COMIDA, NOTA
FROM COMIDAS_FAVORITAS
WHERE LENGTH(NOME_PESSOA) > 10
  AND NOTA BETWEEN 7 AND 10;
  














