USE ABD_03361_A_Nilson;

DROP TABLE IF EXISTS FAMILIA;

CREATE TABLE FAMILIA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    PARENTESCO VARCHAR(50) NOT NULL,
    IDADE INT,
    CIDADE VARCHAR(50)
);

INSERT INTO FAMILIA (NOME, PARENTESCO, IDADE, CIDADE)
VALUES ('Sergio', 'Pai', 89, 'São Paulo'),
       ('Laura', 'Mãe', 85, 'São Paulo'),
       ('Jacqueline', 'Irmã', 45, 'São Paulo'),
       ('Vitor', 'Filho', 28, 'São Paulo'),
       ('Vinicius', 'Filho', 10, 'São Paulo'),
       ('Fernanda Albuquerque', 'Prima', 30, 'São Paulo'),
       ('Rodrigo da Silva', 'Tio', 50, 'Rio de Janeiro'),
       ('Camila Fernandes', 'Prima', 17, 'São Paulo');

-- 1 ESCREVA UM SCRIPT QUE RETORNE SOMENTE AS PESSOAS MAIORES DE 35 ANOS
SELECT * FROM FAMILIA WHERE IDADE > 35;

-- 2 ESCREVA UM SCRIPT QUE RETORNE SOMENTE A CIDADE DE SÃO PAULO: USE LIKE
SELECT * FROM FAMILIA WHERE  CIDADE LIKE 'São Paulo';

-- 3 ESCREVA UM SCRIPT QUE RETORNE AS PESSOAS QUE TEM IDADE ENTRE 18 E 20 ANOS DICA: BETWEEN
SELECT * FROM FAMILIA WHERE  IDADE BETWEEN 18 AND 20;

-- 4 ESCREVA UM SCRIPT QUE RETORNE SOMENTE AS PESSOAS MAIOR E IGUAL A 22 ANOS DICA >=
SELECT * FROM FAMILIA WHERE IDADE >= 22;

-- 5 SOMENTE O NOME E IDADE DAS PESSOAS MENORES QUE 18 ANOS ORDENADOS ASCENDENTEMENTE
SELECT NOME, IDADE 
FROM FAMILIA
WHERE IDADE < 18
ORDER BY IDADE ASC;

-- 6 PESSOAS QUE MORAM EM SÃO PAULO OU RIO DE JANEIRO dICA: COLUNA IN ('LOCAL 1', 'LOCAL 2', 'LOCAL 3')
SELECT *
FROM FAMILIA
WHERE CIDADE IN ('São Paulo', 'Rio de Janeiro');

-- 7 NOME E IDADE DE PESSOAS QUE O NOME SEJA MAIOR QUE 15 CARACTERES E QUE A CIDADE SEJA SÃO PAULO EM ORDEM ASC.
SELECT NOME, IDADE
FROM FAMILIA
WHERE CHAR_LENGTH(NOME) > 15
  AND CIDADE = 'São Paulo'
ORDER BY IDADE ASC;

SELECT * FROM FAMILIA;














