CREATE DATABASE ABD_03361_A_Nilson;

USE ABD_03361_A_Nilson;

CREATE TABLE FAMILIA (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
PARENTESCO VARCHAR(50) NOT NULL,
IDADE INT,
CIDADE VARCHAR(50)
);

INSERT INTO FAMILIA (NOME, PARENTESCO, IDADE, CIDADE) 
VALUES ('Sergio', 'Pai', 89, 'São Paulo');

INSERT INTO FAMILIA (NOME, PARENTESCO, IDADE, CIDADE) 
VALUES ('Laura', 'Mãe', 85, 'São Paulo');

INSERT INTO FAMILIA (NOME, PARENTESCO, IDADE, CIDADE) 
VALUES ('Jacqueline', 'Irmã', 45, 'São Paulo');

INSERT INTO FAMILIA (NOME, PARENTESCO, IDADE, CIDADE) 
VALUES ('Vitor', 'Filho', 28, 'São Paulo');

INSERT INTO FAMILIA (NOME, PARENTESCO, IDADE, CIDADE) 
VALUES ('Vinicius', 'Filho', 10, 'São Paulo');

